version: "1.0"
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app/api

  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./ui/.env
    volumes:
      - ./ui:/app/ui
