version: "1.0"
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
      --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  api:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app/api

  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./ui/.env
    volumes:
      - ./ui:/app/ui
